/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.agentscope.dataagent.insight.service;

import static org.assertj.core.api.Assertions.assertThat;

import io.agentscope.dataagent.insight.domain.InsightStatus;
import io.agentscope.dataagent.insight.persistence.jpa.InsightBatchEntity;
import io.agentscope.dataagent.insight.persistence.jpa.InsightBatchRepository;
import io.agentscope.dataagent.insight.persistence.jpa.InsightEvidenceEntity;
import io.agentscope.dataagent.insight.persistence.jpa.InsightEvidenceRepository;
import io.agentscope.dataagent.insight.persistence.jpa.InsightItemEntity;
import io.agentscope.dataagent.insight.persistence.jpa.InsightItemRepository;
import io.agentscope.dataagent.insight.persistence.jpa.LegacyH2InsightStatusColumnRepair;
import java.time.Instant;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.persistence.autoconfigure.EntityScan;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.jdbc.core.JdbcTemplate;

@SpringBootTest(
        classes = LegacyH2InsightStatusColumnRepairTest.JpaConfig.class,
        webEnvironment = SpringBootTest.WebEnvironment.NONE,
        properties = {
            "spring.datasource.url=jdbc:h2:mem:legacyInsightStatusRepair;MODE=MYSQL;DB_CLOSE_DELAY=-1",
            "spring.datasource.driver-class-name=org.h2.Driver",
            "spring.datasource.username=sa",
            "spring.datasource.password=",
            "spring.jpa.hibernate.ddl-auto=none",
            "spring.sql.init.mode=never",
            "spring.autoconfigure.exclude=org.springframework.boot.micrometer.metrics.autoconfigure.MetricsAutoConfiguration"
        })
class LegacyH2InsightStatusColumnRepairTest {

    @Autowired private JdbcTemplate jdbcTemplate;
    @Autowired private InsightItemRepository itemRepository;
    @Autowired private LegacyH2InsightStatusColumnRepair repair;

    @Test
    void repairsLegacyH2EnumStorageSoJpaQueriesWorkAgain() {
        jdbcTemplate.execute(
                """
                CREATE TABLE insight_batch (
                    row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    completed_at TIMESTAMP WITH TIME ZONE,
                    trigger_type VARCHAR(32) NOT NULL,
                    status VARCHAR(32) NOT NULL,
                    scanned_sources INT,
                    generated_items INT,
                    error_count INT,
                    error_message VARCHAR(2000)
                )
                """);
        jdbcTemplate.execute(
                """
                CREATE TABLE insight_item (
                    row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    baseline_value FLOAT NOT NULL,
                    candidate_json CLOB,
                    conclusion CLOB,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    current_value FLOAT NOT NULL,
                    dimension_name VARCHAR(128),
                    dimension_value VARCHAR(256),
                    evidence_summary VARCHAR(1000),
                    fingerprint VARCHAR(256) NOT NULL,
                    follow_up_json CLOB,
                    kind VARCHAR(32) NOT NULL,
                    metric_key VARCHAR(128) NOT NULL,
                    metric_label VARCHAR(128),
                    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    source_id VARCHAR(128) NOT NULL,
                    status ENUM('0', '1', '2') NOT NULL,
                    summary VARCHAR(1000) NOT NULL,
                    title VARCHAR(300) NOT NULL,
                    window_end TIMESTAMP WITH TIME ZONE NOT NULL,
                    window_start TIMESTAMP WITH TIME ZONE NOT NULL,
                    batch_row_id BIGINT NOT NULL
                )
                """);
        jdbcTemplate.execute(
                """
                CREATE TABLE insight_evidence (
                    row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    detail_text VARCHAR(2000),
                    evidence_key VARCHAR(128) NOT NULL,
                    label VARCHAR(256) NOT NULL,
                    snapshot_json CLOB,
                    value_text VARCHAR(512),
                    item_row_id BIGINT NOT NULL
                )
                """);
        jdbcTemplate.execute(
                """
                CREATE INDEX ix_insight_item_source_status
                    ON insight_item(source_id, status)
                """);
        jdbcTemplate.execute(
                """
                INSERT INTO insight_batch(
                    row_id, started_at, completed_at, trigger_type, status, scanned_sources, generated_items
                ) VALUES (
                    1,
                    TIMESTAMP WITH TIME ZONE '2026-06-30 09:00:00+00',
                    TIMESTAMP WITH TIME ZONE '2026-06-30 09:01:00+00',
                    'scheduled',
                    'SUCCESS',
                    1,
                    1
                )
                """);
        jdbcTemplate.execute(
                """
                INSERT INTO insight_item(
                    row_id, baseline_value, candidate_json, conclusion, created_at, current_value,
                    dimension_name, dimension_value, evidence_summary, fingerprint, follow_up_json, kind,
                    metric_key, metric_label, observed_at, source_id, status, summary, title,
                    window_end, window_start, batch_row_id
                ) VALUES (
                    7,
                    4,
                    '{}',
                    '当前退款率 12%，上一窗口 4%。',
                    TIMESTAMP WITH TIME ZONE '2026-06-30 09:31:00+00',
                    12,
                    null,
                    null,
                    '当前退款率 12%，上一窗口 4%。',
                    'shop-demo:refund-rate',
                    '[]',
                    'ANOMALY',
                    'refund_rate',
                    '退款率',
                    TIMESTAMP WITH TIME ZONE '2026-06-30 09:30:00+00',
                    'shop-demo',
                    1,
                    '最近一个窗口退款率高于上一窗口。',
                    '退款率突然抬升',
                    TIMESTAMP WITH TIME ZONE '2026-06-30 09:30:00+00',
                    TIMESTAMP WITH TIME ZONE '2026-06-29 09:30:00+00',
                    1
                )
                """);

        assertThat(
                        jdbcTemplate.queryForObject(
                                "select status from insight_item where row_id = 7", String.class))
                .isIn("0", "1", "2");

        repair.repairIfNeeded();

        assertThat(
                        jdbcTemplate.queryForObject(
                                "select status from insight_item where row_id = 7", String.class))
                .isEqualTo("CONTINUING");
        assertThat(
                        jdbcTemplate.queryForObject(
                                """
                                select data_type
                                  from information_schema.columns
                                 where table_name = 'INSIGHT_ITEM'
                                   and column_name = 'STATUS'
                                """,
                                String.class))
                .isEqualTo("CHARACTER VARYING");
        assertThat(itemRepository.findById(7L))
                .get()
                .extracting(InsightItemEntity::getStatus)
                .isEqualTo(InsightStatus.CONTINUING);
        assertThat(
                        itemRepository.findBySourceIdAndStatusInOrderByCreatedAtDesc(
                                "shop-demo", List.of(InsightStatus.CONTINUING)))
                .extracting(InsightItemEntity::getRowId)
                .containsExactly(7L);
    }

    @SpringBootConfiguration
    @EnableAutoConfiguration
    @EnableJpaRepositories(
            basePackageClasses = {
                InsightBatchRepository.class,
                InsightItemRepository.class,
                InsightEvidenceRepository.class
            })
    @EntityScan(
            basePackageClasses = {
                InsightBatchEntity.class,
                InsightItemEntity.class,
                InsightEvidenceEntity.class
            })
    @Import(LegacyH2InsightStatusColumnRepair.class)
    static class JpaConfig {}
}
